#!/bin/bash

if [ "$#" -ne 7 ]; then
    echo "Usage: $0 <instance_path> <model_path> <solution_path> <implied_1> <implied_2> <implied_3> <implied_4>"
    exit 1
fi

instance_path=$1
model_path=$2
solution_path=$3
implied_1=$4
implied_2=$5
implied_3=$6
implied_4=$7

./modules/scheduling_solvers/bin/release/checkmspsp2 \
    -E=timemaxsat --print=1 --print-nonoptimal=0 \
    --implied1=${implied_1} \
    --implied2=${implied_2} \
    --implied3=${implied_3} \
    --implied4=${implied_4} \
    ${instance_path} ${model_path} ${solution_path}